USE [master]
GO

/****** Object:  Database [TicketsApi]    Script Date: 9/03/2022 2:35:18 p. m. ******/
CREATE DATABASE [TicketsApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TicketsApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TicketsApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TicketsApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TicketsApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TicketsApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TicketsApi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TicketsApi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TicketsApi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TicketsApi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TicketsApi] SET ARITHABORT OFF 
GO

ALTER DATABASE [TicketsApi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TicketsApi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TicketsApi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TicketsApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TicketsApi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TicketsApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TicketsApi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TicketsApi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TicketsApi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TicketsApi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TicketsApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TicketsApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TicketsApi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TicketsApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TicketsApi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TicketsApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TicketsApi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TicketsApi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TicketsApi] SET  MULTI_USER 
GO

ALTER DATABASE [TicketsApi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TicketsApi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TicketsApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TicketsApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TicketsApi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TicketsApi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TicketsApi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TicketsApi] SET  READ_WRITE 
GO


